const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Jogador: 0},
	{Sólido: 0},
	{Plataformas: 0},
	{Senóide: 0},
	{Tomate: 0},
	{Teclado: 0},
	{Céu: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{Mouse: 0},
	{Iniciar: 0},
	{Perdeu: 0},
	{Ganhou: 0},
	{TelaHome: 0},
	{Ação: 0},
	{BatataCapanga: 0},
	{marcador: 0},
	{Fixar: 0},
	{animação: 0},
	{Retraril: 0},
	{espinhos: 0},
	{Áudio: 0},
	{TelaPerdeu: 0},
	{AçãoT: 0},
	{TomatePodre: 0},
	{Pontos: 0}
];

self.InstanceType = {
	Jogador: class extends self.ISpriteInstance {},
	Plataformas: class extends self.ITiledBackgroundInstance {},
	Tomate: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Céu: class extends self.ITiledBackgroundInstance {},
	Pontuação: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Iniciar: class extends self.ISpriteInstance {},
	Perdeu: class extends self.ISpriteInstance {},
	Ganhou: class extends self.ISpriteInstance {},
	TelaHome: class extends self.ISpriteInstance {},
	BatataCapanga: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	animação: class extends self.ISpriteInstance {},
	Retraril: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	TelaPerdeu: class extends self.ISpriteInstance {},
	TomatePodre: class extends self.ISpriteInstance {}
}